version: '3.8'

services:
  go-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lazy-invoice-app
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
